packages:
  - apps/*
  - crates/*
  - packages/*
ignoredBuiltDependencies:
  - '@firebase/util'
  - es5-ext
  - msgpackr-extract
  - protobufjs
  - svelte-preprocess
  - ttf2woff2
includeWorkspaceRoot: true
onlyBuiltDependencies:
  - argon2
  - esbuild
  - sharp
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
