include: package:leancode_lint/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**/__generated__/**'
linter:
  rules:
    avoid_types_on_closure_parameters: false
    discarded_futures: true
    type_annotate_public_apis: false
    unsafe_variance: false
formatter:
  page_width: 120
