include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
  exclude: 
    - '**/__generated__/**'
linter:
  rules:
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
formatter:
  page_width: 120
