name: typie
description: Typie mobile app
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  assorted_layout_widgets: ^11.0.0
  auto_route: ^10.0.1
  back_button_interceptor: ^8.0.4
  built_value: ^8.9.5
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  dio: ^5.8.0+1
  dio_http2_adapter: ^2.6.0
  envied: ^1.1.1
  ferry: ^0.16.1+2
  ferry_flutter: ^0.9.1-dev.4
  file_picker: ^10.1.9
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.2.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  gql_code_builder_serializers: ^0.1.0
  gql_dio_link: ^1.0.1+1
  gql_exec: ^1.0.0+1
  gql_link: ^1.0.0+1
  gql_transform_link: ^1.0.0
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0+1
  injectable: ^2.5.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  json_annotation: ^4.9.0
  kakao_flutter_sdk_user: ^1.9.7+3
  logger: ^2.5.0
  luthor: ^0.6.1
  mime: ^2.0.0
  naver_login_sdk: ^3.0.0
  permission_handler: ^12.0.0+1
  sign_in_with_apple: ^7.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web_socket: ^1.0.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  envied_generator: ^1.1.1
  ferry_generator: ^0.14.0-dev.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  freezed_lint: ^0.0.9
  hive_ce_generator: ^1.9.1
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/brands/
  - assets/logos/

  fonts:
    - family: LucideIcons
      fonts:
        - asset: assets/fonts/LucideIcons.ttf
    - family: LucideLightIcons
      fonts:
        - asset: assets/fonts/LucideLightIcons.ttf
    - family: LucideBoldIcons
      fonts:
        - asset: assets/fonts/LucideBoldIcons.ttf
    - family: TypieIcons
      fonts:
        - asset: assets/fonts/TypieIcons.ttf
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-Heavy.ttf
          weight: 900
    - family: Eulyoo1945
      fonts:
        - asset: assets/fonts/Eulyoo1945-Regular.ttf
          weight: 400
        - asset: assets/fonts/Eulyoo1945-SemiBold.ttf
          weight: 600
