machine:
  install:
    disk: /dev/vda
    image: factory.talos.dev/metal-installer/d16652227f171d277b6bd35af6f88ce5d9d48906f80a938476b5fea6e7803e6b:v1.11.2

  kernel:
    modules:
      - name: zfs

  network:
    interfaces:
      - deviceSelector:
          busPath: '0*'
        dhcp: true
    nameservers:
      - 1.1.1.1
      - 1.0.0.1

  features:
    hostDNS:
      forwardKubeDNSToHost: false
      resolveMemberNames: true

cluster:
  network:
    cni:
      name: none
    podSubnets:
      - 10.10.0.0/16
    serviceSubnets:
      - 10.20.0.0/16

  apiServer:
    extraArgs:
      enable-aggregator-routing: 'true'
      oidc-issuer-url: https://dex.typie.io
      oidc-client-id: kubernetes
      oidc-username-claim: email
      oidc-groups-claim: groups

    admissionControl:
      - name: PodSecurity
        configuration:
          defaults:
            audit: privileged
            enforce: privileged
            warn: privileged

  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0

  scheduler:
    extraArgs:
      bind-address: 0.0.0.0

  proxy:
    disabled: true
