name: Build

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: The app to build.
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}
        description: The version of the built image.

permissions:
  contents: read
  packages: write

env:
  TURBO_TEAM: penxle
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_CACHE: remote:rw

jobs:
  build:
    name: Build
    runs-on: linux-arm64-4vcpu

    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run turbo run build --filter=@typie/${{ inputs.app }}
        env:
          NODE_ENV: production

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: apps/${{ inputs.app }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
