name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-api:
    name: Build (api)
    uses: ./.github/workflows/build.yml
    with:
      app: api

  build-website:
    name: Build (website)
    uses: ./.github/workflows/build.yml
    with:
      app: website

  deploy-dev:
    name: Deployment (dev)
    needs: [build-api, build-website]
    uses: ./.github/workflows/deployment.yml
    with:
      stack: dev
      version: ${{ needs.build-api.outputs.version }}
    secrets: inherit
